/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 triggerFrog.gltf --transform 
Files: triggerFrog.gltf [242.67MB] > C:\Users\mohan\Downloads\sir_frog_chrono_trigger\triggerFrog-transformed.glb [16.25MB] (93%)
Author: Adrian Carter (https://sketchfab.com/Adrian.Carter3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sir-frog-chrono-trigger-0af0c15e947143be8fab274841764bf1
Title: Sir Frog - Chrono Trigger
*/

import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/triggerFrog-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Sword_low_Sword_0.geometry}
        material={materials.Sword}
        scale={0.05}
        position={[0, -3, 0]}
      />
      <mesh
        geometry={nodes.Sack_low_Sack1_0.geometry}
        material={materials.Sack1}
        scale={0.05}
        position={[0, -3, 0]}
      />
      <mesh
        geometry={nodes.ShieldWeld_low_Shield2_0.geometry}
        material={materials.Shield2}
        scale={0.05}
        position={[0, -3, 0]}
      />
      <mesh
        geometry={nodes.Sheath_low_Sheath1_0.geometry}
        material={materials.Sheath1}
        scale={0.05}
        position={[0, -3, 0]}
      />
      <mesh
        geometry={nodes.AO_lacrima1_lambert20SG6_0.geometry}
        material={materials.lacrima1_lambert20SG6}
        scale={0.05}
        position={[0, -3, 0]}
      />
      <mesh
        geometry={nodes.ArmorBackBorder_low_ArmorBack2_0.geometry}
        material={materials.ArmorBack2}
        scale={0.05}
        position={[0, -3, 0]}
      />
      <mesh
        geometry={nodes.ArmorFront1_low_ChestArmorFront2_0.geometry}
        material={materials.ChestArmorFront2}
        scale={0.05}
        position={[0, -3, 0]}
      />
      <mesh
        geometry={nodes.BeltBuckle_low_Belt2_0.geometry}
        material={materials.Belt2}
        scale={0.05}
        position={[0, -3, 0]}
      />
      <mesh
        geometry={nodes.EyeLeft_MI_EyeRefractive_Inst_L2_0.geometry}
        material={materials.MI_EyeRefractive_Inst_L2}
        scale={0.05}
        position={[0, -3, 0]}
      />
      <mesh
        geometry={nodes.EyeRight_MI_EyeRefractive_Inst_R2_0.geometry}
        material={materials.MI_EyeRefractive_Inst_R2}
        scale={0.05}
        position={[0, -3, 0]}
      />
      <mesh
        geometry={nodes.Gloves_low_Gloves2_0.geometry}
        material={materials.Gloves2}
        scale={0.05}
        position={[0, -3, 0]}
      />
      <mesh
        geometry={nodes.Lacrima_lacrima1_lambert20SG7_0.geometry}
        material={materials.lacrima1_lambert20SG7}
        scale={0.05}
        position={[0, -3, 0]}
      />
      <mesh
        geometry={nodes.PantsCuffs_low_Pants2_0.geometry}
        material={materials.Pants2}
        scale={0.05}
        position={[0, -3, 0]}
      />
      <mesh
        geometry={nodes.Scarf_low_Scarf2_0.geometry}
        material={materials.Scarf2}
        scale={0.05}
        position={[0, -3, 0]}
      />
      <mesh
        geometry={nodes.ShoeSoles_low_Shoes2_0.geometry}
        material={materials.Shoes2}
        scale={0.05}
        position={[0, -3, 0]}
      />
      <mesh
        geometry={nodes.SirFrog_low_Face2_0.geometry}
        material={materials.Face2}
        scale={0.05}
        position={[0, -3, 0]}
      />
      <mesh
        geometry={nodes.SirFrog_low_Extras2_0.geometry}
        material={materials.Extras2}
        scale={0.05}
        position={[0, -3, 0]}
      />
      <mesh
        geometry={nodes.SirFrog_low_Legs2_0.geometry}
        material={materials.Legs2}
        scale={0.05}
        position={[0, -3, 0]}
      />
      <mesh
        geometry={nodes.SirFrog_low_Body2_0.geometry}
        material={materials.Body2}
        scale={0.05}
        position={[0, -3, 0]}
      />
      <mesh
        geometry={nodes.SirFrog_low_Arms2_0.geometry}
        material={materials.Arms2}
        scale={0.05}
        position={[0, -3, 0]}
      />
      <mesh
        geometry={nodes.Cape_low1_Cape_low1_0.geometry}
        material={materials.Cape_low1}
        scale={0.05}
        position={[0, -3, 0]}
      />
    </group>
  );
}

useGLTF.preload("/triggerFrog-transformed.glb");
